use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use anyhow::{bail, Context, Result};
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use semver::Version;
use sha2::{Digest, Sha256};
use tokio::sync::Notify;
use tokio::time;
use tracing::{info, warn};

const DEFAULT_CHECK_INTERVAL_SECS: u64 = 6 * 60 * 60; // 6 hours
const INITIAL_DELAY_SECS: u64 = 60;
const GITHUB_RELEASES_URL: &str =
    "https://api.github.com/repos/sestinj/threader/releases/latest";

/// Ed25519 public key for verifying release signatures.
/// Replace this with the actual public key generated by `scripts/generate-signing-key.sh`.
const RELEASE_PUBLIC_KEY_BASE64: &str = "g0u3+ZM8mL7xJyYaKip6TBeRUfYi3hTduJ2Z8LuoCH0=";

/// Detected install method determines whether auto-update is supported.
#[derive(Debug, PartialEq)]
pub enum InstallMethod {
    /// Direct binary download — supports auto-update.
    Direct,
    /// Installed via Homebrew — notify only.
    Homebrew,
    /// Installed via `cargo install` — notify only.
    Cargo,
}

impl InstallMethod {
    pub fn detect() -> Self {
        let exe = match std::env::current_exe() {
            Ok(p) => p.to_string_lossy().to_string(),
            Err(_) => return InstallMethod::Direct,
        };
        if exe.contains("/Cellar/") || exe.contains("/homebrew/") {
            InstallMethod::Homebrew
        } else if exe.contains("/.cargo/bin/") {
            InstallMethod::Cargo
        } else {
            InstallMethod::Direct
        }
    }
}

/// Information about a GitHub release.
#[derive(Debug)]
struct ReleaseInfo {
    version: Version,
    tarball_url: String,
    sig_url: String,
    sha256_url: String,
}

/// Background auto-updater that checks GitHub releases periodically.
pub struct AutoUpdater {
    pub restart_notify: Arc<Notify>,
    client: reqwest::Client,
}

impl AutoUpdater {
    pub fn new(restart_notify: Arc<Notify>) -> Self {
        Self {
            restart_notify,
            client: reqwest::Client::new(),
        }
    }

    /// Run the auto-update loop. Never returns under normal operation.
    pub async fn run(&self) -> Result<()> {
        if std::env::var("THREADER_NO_AUTO_UPDATE").unwrap_or_default() == "1" {
            info!("Auto-update disabled via THREADER_NO_AUTO_UPDATE");
            return Ok(());
        }

        let install_method = InstallMethod::detect();
        if install_method != InstallMethod::Direct {
            info!(
                "Install method {:?} detected — auto-update will only notify",
                install_method
            );
        }

        // Initial delay before first check
        time::sleep(Duration::from_secs(INITIAL_DELAY_SECS)).await;

        let interval = check_interval();
        info!("Auto-updater started, checking every {}s", interval.as_secs());

        loop {
            match self.check_and_update(&install_method).await {
                Ok(true) => {
                    info!("Update applied, requesting restart");
                    return Ok(());
                }
                Ok(false) => {} // no update needed
                Err(e) => {
                    warn!("Update check failed: {}", e);
                }
            }
            time::sleep(interval).await;
        }
    }

    /// Check for a new release and apply it if available.
    /// Returns Ok(true) if an update was applied and restart is needed.
    pub async fn check_and_update(&self, install_method: &InstallMethod) -> Result<bool> {
        let current = current_version()?;
        let release = self.fetch_latest_release().await?;

        if release.version <= current {
            info!(
                "Current version {} is up to date (latest: {})",
                current, release.version
            );
            return Ok(false);
        }

        info!(
            "New version available: {} -> {}",
            current, release.version
        );

        if *install_method != InstallMethod::Direct {
            let hint = match install_method {
                InstallMethod::Homebrew => "brew upgrade threader",
                InstallMethod::Cargo => "cargo install threader",
                InstallMethod::Direct => unreachable!(),
            };
            info!(
                "Threader {} is available. Update with: {}",
                release.version, hint
            );
            return Ok(false);
        }

        self.download_and_install(&release).await?;

        // Re-run init to pick up any new features (hooks, URL scheme, etc.)
        if let Err(e) = crate::cli::init::init_core() {
            warn!("Post-update init failed: {}", e);
        }

        self.trigger_restart()?;
        Ok(true)
    }

    /// Fetch the latest release info from GitHub.
    async fn fetch_latest_release(&self) -> Result<ReleaseInfo> {
        let current = current_version()?;
        let resp: serde_json::Value = self
            .client
            .get(GITHUB_RELEASES_URL)
            .header("User-Agent", format!("threader/{}", current))
            .send()
            .await?
            .error_for_status()
            .context("GitHub releases API request failed")?
            .json()
            .await?;

        let tag = resp["tag_name"]
            .as_str()
            .context("missing tag_name in release")?;
        let version_str = tag.strip_prefix('v').unwrap_or(tag);
        let version = Version::parse(version_str)
            .with_context(|| format!("invalid version in tag: {}", tag))?;

        let asset_name = platform_asset_name();
        let assets = resp["assets"]
            .as_array()
            .context("missing assets in release")?;

        let tarball_name = format!("{}.tar.gz", asset_name);
        let sig_name = format!("{}.tar.gz.sig", asset_name);
        let sha256_name = format!("{}.tar.gz.sha256", asset_name);

        let find_url = |name: &str| -> Result<String> {
            assets
                .iter()
                .find(|a| a["name"].as_str() == Some(name))
                .and_then(|a| a["browser_download_url"].as_str())
                .map(|s| s.to_string())
                .with_context(|| format!("asset {} not found in release", name))
        };

        Ok(ReleaseInfo {
            version,
            tarball_url: find_url(&tarball_name)?,
            sig_url: find_url(&sig_name)?,
            sha256_url: find_url(&sha256_name)?,
        })
    }

    /// Download, verify, and install the update.
    async fn download_and_install(&self, release: &ReleaseInfo) -> Result<()> {
        let tmp_dir = tmp_update_dir()?;
        std::fs::create_dir_all(&tmp_dir)?;

        // Download tarball, signature, and checksum in parallel
        let tarball_path = tmp_dir.join("update.tar.gz");
        let sig_path = tmp_dir.join("update.tar.gz.sig");

        info!("Downloading update v{}...", release.version);

        let tarball_bytes = self.download_file(&release.tarball_url).await?;
        let sig_bytes = self.download_file(&release.sig_url).await?;
        let sha256_text = self
            .client
            .get(&release.sha256_url)
            .send()
            .await?
            .error_for_status()?
            .text()
            .await?;

        // Write tarball to disk for extraction
        std::fs::write(&tarball_path, &tarball_bytes)?;
        std::fs::write(&sig_path, &sig_bytes)?;

        // Verify Ed25519 signature
        info!("Verifying Ed25519 signature...");
        verify_signature(&tarball_bytes, &sig_bytes)?;

        // Verify SHA256 checksum (defense in depth)
        info!("Verifying SHA256 checksum...");
        verify_sha256(&tarball_bytes, &sha256_text)?;

        // Extract binary
        info!("Extracting update...");
        let extract_dir = tmp_dir.join("extracted");
        std::fs::create_dir_all(&extract_dir)?;

        let status = std::process::Command::new("tar")
            .args(["xzf", &tarball_path.to_string_lossy()])
            .arg("-C")
            .arg(&extract_dir)
            .status()
            .context("failed to run tar")?;

        if !status.success() {
            bail!("tar extraction failed");
        }

        // Find the extracted binary
        let asset_name = platform_asset_name();
        let new_binary = extract_dir.join(&asset_name);
        if !new_binary.exists() {
            bail!(
                "expected binary {} not found in archive",
                new_binary.display()
            );
        }

        // Set executable permissions
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&new_binary, std::fs::Permissions::from_mode(0o755))?;
        }

        // Replace current binary
        let current_exe =
            std::env::current_exe().context("could not determine current binary path")?;

        // Keep backup
        let backup = current_exe.with_extension("bak");
        if backup.exists() {
            let _ = std::fs::remove_file(&backup);
        }

        // Try rename first (atomic), fall back to copy for cross-device
        if let Err(_) = std::fs::rename(&current_exe, &backup) {
            std::fs::copy(&current_exe, &backup)?;
        }

        if let Err(e) = std::fs::rename(&new_binary, &current_exe) {
            warn!("Atomic rename failed, falling back to copy: {}", e);
            std::fs::copy(&new_binary, &current_exe)
                .context("failed to copy new binary into place")?;

            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                std::fs::set_permissions(
                    &current_exe,
                    std::fs::Permissions::from_mode(0o755),
                )?;
            }
        }

        // Clean up temp files
        let _ = std::fs::remove_dir_all(&tmp_dir);

        info!("Update installed successfully (v{})", release.version);
        Ok(())
    }

    async fn download_file(&self, url: &str) -> Result<Vec<u8>> {
        let bytes = self
            .client
            .get(url)
            .send()
            .await?
            .error_for_status()
            .with_context(|| format!("download failed: {}", url))?
            .bytes()
            .await?;
        Ok(bytes.to_vec())
    }

    /// Spawn a delayed restart and notify the daemon to shut down.
    fn trigger_restart(&self) -> Result<()> {
        let exe = std::env::current_exe().context("could not determine binary path")?;
        let exe_str = exe.to_string_lossy().to_string();

        // Spawn a detached process that waits then starts the new daemon
        std::process::Command::new("sh")
            .args(["-c", &format!("sleep 2 && '{}' start", exe_str)])
            .stdin(std::process::Stdio::null())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
            .context("failed to spawn restart process")?;

        self.restart_notify.notify_one();
        Ok(())
    }
}

/// Run a one-shot update check (for `threader update` CLI command).
pub async fn run_manual_update() -> Result<()> {
    let install_method = InstallMethod::detect();
    let notify = Arc::new(Notify::new());
    let updater = AutoUpdater::new(notify);

    let current = current_version()?;
    println!("Current version: {}", current);
    println!("Checking for updates...");

    let release = updater.fetch_latest_release().await?;

    if release.version <= current {
        println!("Already up to date (v{})", current);
        // Always re-run init to ensure hooks match the current binary
        println!("Reinitializing hooks...");
        crate::cli::init::init_core()?;
        return Ok(());
    }

    println!("New version available: v{}", release.version);

    if install_method != InstallMethod::Direct {
        let hint = match install_method {
            InstallMethod::Homebrew => "brew upgrade threader",
            InstallMethod::Cargo => "cargo install threader",
            InstallMethod::Direct => unreachable!(),
        };
        println!("Update with: {}", hint);
        // Re-run init so hooks point to the current binary with correct args
        println!("Reinitializing hooks...");
        crate::cli::init::init_core()?;
        return Ok(());
    }

    println!("Downloading and installing...");
    updater.download_and_install(&release).await?;

    // Re-run init to pick up any new features (hooks, URL scheme, etc.)
    println!("Reinitializing hooks...");
    crate::cli::init::init_core()?;

    println!("Updated to v{}!", release.version);

    // Restart the daemon if it's running
    let exe = std::env::current_exe().context("could not determine binary path")?;
    let exe_str = exe.to_string_lossy().to_string();
    let status = std::process::Command::new(&exe_str)
        .arg("stop")
        .status();
    if status.is_ok() {
        println!("Restarting daemon...");
        std::process::Command::new(&exe_str)
            .arg("start")
            .status()
            .ok();
    }

    Ok(())
}

fn current_version() -> Result<Version> {
    Version::parse(env!("CARGO_PKG_VERSION")).context("invalid CARGO_PKG_VERSION")
}

fn check_interval() -> Duration {
    let secs = std::env::var("THREADER_UPDATE_INTERVAL_SECS")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(DEFAULT_CHECK_INTERVAL_SECS);
    Duration::from_secs(secs)
}

fn platform_asset_name() -> String {
    let os = match std::env::consts::OS {
        "macos" => "darwin",
        other => other,
    };
    let arch = match std::env::consts::ARCH {
        "aarch64" => "arm64",
        other => other,
    };
    format!("threader-{}-{}", os, arch)
}

fn tmp_update_dir() -> Result<PathBuf> {
    let home = dirs::home_dir().context("could not determine home directory")?;
    Ok(home.join(".threader").join("tmp-update"))
}

/// Verify the Ed25519 signature of data against the hardcoded public key.
fn verify_signature(data: &[u8], sig_bytes: &[u8]) -> Result<()> {
    use base64::Engine;

    let pub_key_bytes = base64::engine::general_purpose::STANDARD
        .decode(RELEASE_PUBLIC_KEY_BASE64)
        .context("failed to decode hardcoded public key")?;

    let pub_key_array: [u8; 32] = pub_key_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("public key must be 32 bytes"))?;

    let verifying_key = VerifyingKey::from_bytes(&pub_key_array)
        .context("invalid Ed25519 public key")?;

    let sig_array: [u8; 64] = sig_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("signature must be 64 bytes"))?;
    let signature = Signature::from_bytes(&sig_array);

    verifying_key
        .verify(data, &signature)
        .context("Ed25519 signature verification failed — update aborted")?;

    info!("Signature verified successfully");
    Ok(())
}

/// Verify SHA256 checksum. The checksum file format is `<hash>  <filename>` or just `<hash>`.
fn verify_sha256(data: &[u8], expected_text: &str) -> Result<()> {
    let expected_hash = expected_text
        .split_whitespace()
        .next()
        .context("empty checksum file")?
        .to_lowercase();

    let mut hasher = Sha256::new();
    hasher.update(data);
    let actual_hash = format!("{:x}", hasher.finalize());

    if actual_hash != expected_hash {
        bail!(
            "SHA256 mismatch: expected {}, got {}",
            expected_hash,
            actual_hash
        );
    }

    info!("SHA256 checksum verified");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_platform_asset_name() {
        let name = platform_asset_name();
        assert!(name.starts_with("threader-"));
        // Should contain os and arch
        assert!(name.contains('-'));
    }

    #[test]
    fn test_current_version_parses() {
        let v = current_version().unwrap();
        // Should parse without error
        assert!(v.major == 0 || v.major >= 1);
    }

    #[test]
    fn test_install_method_detect() {
        // In a dev environment, this should return Direct or Cargo
        let method = InstallMethod::detect();
        assert!(
            method == InstallMethod::Direct
                || method == InstallMethod::Cargo
                || method == InstallMethod::Homebrew
        );
    }

    #[test]
    fn test_verify_sha256_valid() {
        let data = b"hello world";
        let mut hasher = Sha256::new();
        hasher.update(data);
        let hash = format!("{:x}", hasher.finalize());
        let checksum_text = format!("{}  test.tar.gz", hash);
        verify_sha256(data, &checksum_text).unwrap();
    }

    #[test]
    fn test_verify_sha256_invalid() {
        let data = b"hello world";
        let result = verify_sha256(data, "0000000000000000000000000000000000000000000000000000000000000000  test.tar.gz");
        assert!(result.is_err());
    }

    #[test]
    fn test_verify_signature_rejects_invalid() {
        // With a placeholder key, signature verification should fail
        let data = b"test data";
        let fake_sig = [0u8; 64];
        // This will fail because the hardcoded key is a placeholder
        let result = verify_signature(data, &fake_sig);
        assert!(result.is_err());
    }
}
